/**
 *        -  -  -  -  RolDicer  -  -  -  -
 *
 *  I am not responsible for the problems that this program may cause.
 *
 *      @author Fernando Pérez Gutiérrez fernaperg@gmail.com
 *
 *  For more visit: https://github.com/fernaper
 *  Full project: https://github.com/fernaper/RolDicer
 *
 *  2018 (c) fernaperg
 *
 */
package com.roldicer.view;

import com.roldicer.controller.Controller;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ResourceBundle;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Fernando Pérez Gutiérrez <fernaperg@gmail.com>
 */
public class NewTemplate extends javax.swing.JFrame {

    private Component selected;
    private int widthSelected;
    private int heightSelected;

    private Controller controller;
    private String language;
    private ResourceBundle bundle;

    private final ButtonGroup group;

    /**
     * Creates new form NewTemplate
     *
     * @param controller
     * @param language
     */
    public NewTemplate(Controller controller, String language) {
        this.controller = controller;
        this.language = "";
        initComponents();
        updateLanguage(language);
        this.language = language;
        this.group = new ButtonGroup();
        this.group.add(esEs);
        this.group.add(enEn);
    }

    public NewTemplate() {
        initComponents();
        this.language = "";
        updateLanguage("es_Es");
        this.language = "es_Es";
        this.group = new ButtonGroup();
        this.group.add(esEs);
        this.group.add(enEn);
    }

    private void updateLanguage(String language) {
        if (this.language.equals(language)) {
            return;
        }

        ResourceBundle bndl = Controller.readBundle(language);

        if (bndl == null) {
            return;
        }

        this.bundle = bndl;
        this.language = language;

        this.setTitle(Controller.TITLE + " - " + this.bundle.getString("Idiom"));
        this.jMenu1.setText(this.bundle.getString("File"));
        this.jMenu2.setText(this.bundle.getString("Edit"));
        this.selectLanguage.setText(this.bundle.getString("Language"));
    }

    public void addButton(JButton jbutton) {
        this.jPanel2.add(jbutton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        dadoTemplate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        selectLanguage = new javax.swing.JMenu();
        esEs = new javax.swing.JRadioButtonMenuItem();
        enEn = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(230, 2));

        dadoTemplate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button.png"))); // NOI18N
        dadoTemplate.setBorder(null);
        dadoTemplate.setContentAreaFilled(false);
        dadoTemplate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dadoTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadoTemplateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dadoTemplate)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dadoTemplate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(2, 230));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jMenu1.setText("File");

        selectLanguage.setText("Language");

        esEs.setSelected(true);
        esEs.setText("Español");
        esEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esEsActionPerformed(evt);
            }
        });
        selectLanguage.add(esEs);

        enEn.setSelected(true);
        enEn.setText("English");
        enEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enEnActionPerformed(evt);
            }
        });
        selectLanguage.add(enEn);

        jMenu1.add(selectLanguage);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dadoTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadoTemplateActionPerformed
        this.selected = Generator.button();
    }//GEN-LAST:event_dadoTemplateActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        Dimension d = Generator.dimButton();

        if (this.selected == null
                || evt.getX() - (int) (d.getWidth() / 2) < 0
                || evt.getY() - (int) (d.getHeight() / 2) < 0) {
            return;
        }

        this.jPanel2.add(this.selected, new AbsoluteConstraints((int) (evt.getX() - (d.getWidth() / 2)), (int) (evt.getY() - (d.getHeight() / 2)), -1, -1));
        this.selected = null;

        Dimension minSize = this.jPanel2.getMinimumSize();
        this.setMinimumSize(new Dimension(Math.max(800, (int) minSize.getWidth() + 259), Math.max(620, (int) minSize.getHeight() + 108)));
        this.jPanel2.revalidate();
        this.jPanel2.repaint();

    }//GEN-LAST:event_jPanel2MouseClicked

    private void esEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esEsActionPerformed
        updateLanguage("es_Es");
    }//GEN-LAST:event_esEsActionPerformed

    private void enEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enEnActionPerformed
        updateLanguage("en_En");
    }//GEN-LAST:event_enEnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dadoTemplate;
    private javax.swing.JRadioButtonMenuItem enEn;
    private javax.swing.JRadioButtonMenuItem esEs;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenu selectLanguage;
    // End of variables declaration//GEN-END:variables
}
