/**
 *        -  -  -  -  RolDicer  -  -  -  -
 *
 *  I am not responsible for the problems that this program may cause.
 *
 *      @author Fernando Pérez Gutiérrez fernaperg@gmail.com
 *
 *  For more visit: https://github.com/fernaper
 *  Full project: https://github.com/fernaper/RolDicer
 *
 *  2018 (c) fernaperg
 *
 */
package com.roldicer.view;

import java.util.ResourceBundle;
import com.roldicer.controller.Controller;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Fernando Pérez Gutiérrez <fernaperg@gmail.com>
 */
public class Window extends javax.swing.JFrame {

    private final Controller controller;
    private ResourceBundle bundle;
    private String language;

    private ButtonGroup group;

    public Window(Controller controller) {
        this.controller = controller;
        this.language = "";
        //this.bundle = Controller.readBundle(this.language);
        initComponents();
        updateLanguage("es_Es");
        this.language = "es_Es";

        this.group = new ButtonGroup();
        this.group.add(esEs);
        this.group.add(enEn);
    }

    private void updateLanguage(String language) {
        if (this.language.equals(language)) {
            return;
        }

        ResourceBundle bndl = Controller.readBundle(language);

        if (bndl == null) {
            return;
        }

        this.bundle = bndl;
        this.language = language;

        this.setTitle(Controller.TITLE + " - " + this.bundle.getString("Idiom"));
        this.jMenu1.setText(this.bundle.getString("File"));
        this.jMenu2.setText(this.bundle.getString("Edit"));
        this.selectLanguage.setText(this.bundle.getString("Language"));
        this.createTemplate.setText(this.bundle.getString("CreateTemplate"));
        this.editTemplate.setText(this.bundle.getString("EditTemplate"));
        this.loadFile.setText(this.bundle.getString("LoadFile"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createTemplate = new javax.swing.JButton();
        editTemplate = new javax.swing.JButton();
        loadFile = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        selectLanguage = new javax.swing.JMenu();
        esEs = new javax.swing.JRadioButtonMenuItem();
        enEn = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        createTemplate.setText("Create Template");
        createTemplate.setMaximumSize(new java.awt.Dimension(133, 23));
        createTemplate.setMinimumSize(new java.awt.Dimension(133, 23));
        createTemplate.setPreferredSize(new java.awt.Dimension(133, 23));
        createTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTemplateActionPerformed(evt);
            }
        });

        editTemplate.setText("Edit Template");
        editTemplate.setMaximumSize(new java.awt.Dimension(133, 23));
        editTemplate.setMinimumSize(new java.awt.Dimension(133, 23));
        editTemplate.setPreferredSize(new java.awt.Dimension(133, 23));
        editTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTemplateActionPerformed(evt);
            }
        });

        loadFile.setText("Load File");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createTemplate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editTemplate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadFile))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        jMenu1.setText("File");

        selectLanguage.setText("Language");

        esEs.setSelected(true);
        esEs.setText("Español");
        esEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esEsActionPerformed(evt);
            }
        });
        selectLanguage.add(esEs);

        enEn.setSelected(true);
        enEn.setText("English");
        enEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enEnActionPerformed(evt);
            }
        });
        selectLanguage.add(enEn);

        jMenu1.add(selectLanguage);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void esEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esEsActionPerformed
        updateLanguage("es_Es");
    }//GEN-LAST:event_esEsActionPerformed

    private void enEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enEnActionPerformed
        updateLanguage("en_En");
    }//GEN-LAST:event_enEnActionPerformed

    private void createTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTemplateActionPerformed
        controller.setNewTemplate(new NewTemplate(this.controller, this.language));
        controller.clearView();
    }//GEN-LAST:event_createTemplateActionPerformed

    private void editTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTemplateActionPerformed
        
    }//GEN-LAST:event_editTemplateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createTemplate;
    private javax.swing.JButton editTemplate;
    private javax.swing.JRadioButtonMenuItem enEn;
    private javax.swing.JRadioButtonMenuItem esEs;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loadFile;
    private javax.swing.JMenu selectLanguage;
    // End of variables declaration//GEN-END:variables
}
